### ISSUE TITLE
Missing tag information

### ISSUE THREAD

**Issue by tslater** [PKSHATechnology-Research/camphr#112]
I noticed that the spacy tag field is empty. Is this a known issue? It looks like Udify supports some level of ufeats tagging (https://universaldependencies.org/u/feat/index.html)? I wonder if I'm supposed to b getting any of this in Spacy and I have a bug in my setup, or if it just isn't implemented yet? Would it be souced in token.tag like I'm thinking (if it does exist)?

 I also noticed that displacy doesn't render the POS info. I am wondering if that is related?

BTW, just have to say that this is awesome.

**Comment by tamuhey** [comment]
Hi, thank you again for reporting issues!
[Here](https://github.com/PKSHATechnology-Research/camphr-allennlp/blob/4e76487021429357a99fb19cd8ada286bcc43e38/camphr_allennlp/udify.py#L109) is the code that parses Udify's result and add info to each token. As you noticed, `token.tag_` remains empty so this is not a bug. But I cannot remember why I didn't implement that, so I'll find out the reason..

> I also noticed that displacy doesn't render the POS info. I am wondering if that is related?

This maybe a bug, and I'll fix it.

**Comment by ranjita-naik** [comment]
I've created a PR for adding gender and number subtags - ```https://github.com/PKSHATechnology-Research/camphr-allennlp/pull/2```

**Comment by tamuhey** [comment]
https://github.com/PKSHATechnology-Research/camphr-allennlp/pull/2
