### ISSUE TITLE
Gender and number subtags generation

### ISSUE THREAD

**Issue by ranjita-naik** [PKSHATechnology-Research/camphr#146]
I was comparing the default morpho-syntactic tags generated by camphr-udify and https://github.com/Hyperparticle/udify.

```
import spacy
import stanza
from spacy_conll import ConllFormatter

nlp=spacy.load("en_udify")
conllformatter = ConllFormatter(nlp)
nlp.add_pipe(conllformatter, last=True)

doc=nlp("Mother Teresa devoted her entire life to helping others") 
print(doc._.conll_str)

```
```
1	Mother	Mother	PROPN		_	2	compound	_	_
2	Teresa	Teresa	PROPN		_	3	nsubj	_	_
3	devoted	devote	VERB		_	0	root	_	_
4	her	her	PRON		_	6	nmod:poss	_	_
5	entire	entire	ADJ		_	6	amod	_	_
6	life	life	NOUN		_	3	obj	_	_
7	to	to	SCONJ		_	8	mark	_	_
8	helping	help	VERB		_	3	advcl	_	_
9	others	other	NOUN		_	8	obj	_	SpaceAfter=No

```

Tags returned by https://github.com/Hyperparticle/udify, for the same input.
```
prediction:  1  Mother  Mother  PROPN   _       Number=Sing     2       compound        _       _
2       Teresa  Teresa  PROPN   _       Number=Sing     3       nsubj   _       _
3       devoted devote  VERB    _       Mood=Ind|Tense=Past|VerbForm=Fin        0       root    _       _
4       her     her     PRON    _       Gender=Fem|Number=Sing|Person=3|Poss=Yes|PronType=Prs   6       nmod:poss      _                                               _
5       entire  entire  ADJ     _       Degree=Pos      6       amod    _       _
6       life    life    NOUN    _       Number=Sing     3       obj     _       _
7       to      to      SCONJ   _       _       8       mark    _       _
8       helping help    VERB    _       VerbForm=Ger    3       advcl   _       _
9       others  other   NOUN    _       Number=Plur     8       obj     _       _
```

Gender and number subtags are missing in camphr-udify. Could we have those included by default please?

thanks,
Ranjita

**Comment by tamuhey** [comment]
The result `print(doc._.conll_str)` is basically created `spacy.English` model, and added some info from Udify [here](https://github.com/PKSHATechnology-Research/camphr-allennlp/blob/ca766579101f124cdf3656a68e49bec531939643/camphr_allennlp/udify.py#L109).
So if you want to show all result from Udify via `doc._.conll_str`, the output should be set on `doc`, as with other items like `dep_` and `lemma_`. 

PR to add this feature is wellcome!

**Comment by ranjita-naik** [comment]
I've created a PR -https://github.com/PKSHATechnology-Research/camphr-allennlp/pull/2.

**Comment by tamuhey** [comment]
Really appreciate your help, @ranjita-naik !

**Comment by ranjita-naik** [comment]
Could you please publish the updated package?

**Comment by tamuhey** [comment]
I've just published new version of `camphr-allennlp`

**Comment by ranjita-naik** [comment]
Thanks!
