### ISSUE TITLE
How to create your own Udify wrapper

### ISSUE THREAD

**Issue by svlandeg** [PKSHATechnology-Research/camphr#21]
Hi @tamuhey, great work on this repo! :-)

I saw you have this pretrained `en_udify-0.5.tar.gz` model. Where is the code/instructions to make something like that from a different pretrained Udify model? Like e.g. for another language?

**Comment by tamuhey** [comment]
Hi,

1. You can use pretrained Udify model with [Udify.from_archive](https://github.com/PKSHATechnology-Research/camphr/blob/8f8992192e1f32cb84ff184ed77f6df7a6e70775/camphr/pipelines/udify.py#L77).

`archive_path` is the path containing [allennlp Archive object](https://allenai.github.io/allennlp-docs/api/models/archival/#allennlpmodelsarchival).
For example:

```python
import spacy
from camphr.pipelines.udify import Udify
nlp = spacy.blank("en")
pipe = Udify.from_archive("/path/to/udify/archive.tar.gz")
nlp.add_pipe(pipe)
```

2. You can change the tokenizer of `en_udify` with `load_udify`. Please see [the doc](https://camphr.readthedocs.io/en/latest/notes/udify.html#use-udify-with-non-space-delimited-languages) for details.

**Comment by svlandeg** [comment]
Thanks!
