### ISSUE TITLE
Link to logo file is wrong in the pypi.org.

### ISSUE THREAD

**Issue by wakamezake** [PKSHATechnology-Research/camphr#28]
[pypi - camphr](https://pypi.org/project/camphr/)

![logo_missing](https://user-images.githubusercontent.com/7046610/76609320-8b7e6580-655a-11ea-84cd-79c73132989e.PNG)

**Comment by tamuhey** [comment]
Thanks for reporting! I'll try to fix it!

**Comment by tamuhey** [comment]
Fired CI to release new version of camphr: ae1e1ff24316be59d909d7b6243eb762046045ad

**Comment by tamuhey** [comment]
Fixed https://pypi.org/project/camphr/0.5.10.dev0/
