### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by Evpok** [PKSHATechnology-Research/camphr#29]
Camphr is currently pinned at `python < 3.8`, is there a specific reason for this and if so, what can we do to help?

**Edit**: sorry, I just saw #19, still, what can we do to help?

**Comment by tamuhey** [comment]
As you said, I previously worked to support `python3.8` but it is still failing due to [the sentencepiece issue](https://github.com/google/sentencepiece/issues/452).  
I think the best solution is to fix [the sentencepiece issue](https://github.com/google/sentencepiece/issues/452) to support python3.8.
So I'd appreciate if you could fix this issue.

**Comment by Evpok** [comment]
@tamuhey Well, from what I understand, this situation is caused by the combination

1. `sentencepiece` python binding is a pain to install from source (you have to build the C++ lib before, which would be inconvenient if you just want to use camphr)
2. `sentencepiece` has no macos wheel for the latest release (which is why pip tries to install from source, and fails because the C++ lib is not installed)

The issue is only for macos though, and it's not really fixable (unless you have a way to force a new sentencepiece release, but the maintainer does not seem very eager to do that). On the other hand, installing on Linux works fine, so maybe just remove the pin? I won't make any difference for macos users (it still won't work) but at least it will work for Linux users.

**Comment by tamuhey** [comment]
OK, I'll remove the pin for Linux users.

**Comment by tamuhey** [comment]
I fired CI to release `camphr 0.5.10`, and this version is able to be installed with `python>=3.8`, though macos users will still fail.

**Comment by Evpok** [comment]
@tamuhey Thanks a lot! :-)
