### ISSUE TITLE
doc.ents empty, doc.is_nered == False

### ISSUE THREAD

**Issue by jack-rory-staunton** [PKSHATechnology-Research/camphr#57]
I followed the documentation to fine-tune the bert-base-cased (en) ner model and then made a spacy doc with text "Bob Jones and Barack Obama went up the hill in Wisconsin." but the resulting doc has doc.ents = () and doc.is_nered = False. 

Am I missing something?

Thank you!

**Comment by tamuhey** [comment]
Thanks for reporting and I'm sorry for late to reponse.
I've reproduced this bug.

**Comment by jack-rory-staunton** [comment]
that's not true! see my screenshot on the closed issue https://github.com/PKSHATechnology-Research/camphr/issues/51

**Comment by jack-rory-staunton** [comment]
can you show an example where the pipeline recognizes entities?
