### ISSUE TITLE
allennlp==1.0.0 support

### ISSUE THREAD

**Issue by KoichiYasuoka** [PKSHATechnology-Research/camphr#58]
Hi @tamuhey san, [unofficial-allennlp-nightly](https://pypi.org/project/unofficial-allennlp-nightly/) seems to have outdated since [allennlp](https://github.com/allenai/allennlp)==1.0.0 released last week. `pip install -U allennlp` destroys `import_submodules` of `allennlp.common.util` now.

**Comment by KoichiYasuoka** [comment]
Now I realize that UDify-module is hard to integrate into allennlp==1.0.0 since UDify pretrained-model was hard-encoded to allennlp 0.9.x (especially in the parameter `constructor_to_call` and so on). Should we wait to [integrate UDify into allennlp](https://github.com/Hyperparticle/udify/issues/5), or take other ways with spaCy and KNP?

**Comment by tamuhey** [comment]
For now, I'll try to integrate `unofficial-udify` to `allennlp==1.0.0`. 
Here is the PR: https://github.com/tamuhey/udify/pull/1
