### ISSUE TITLE
Bio BERT models NER  fine-tuning error:  "ValueError: Couldn't find any `_TrfMap`" 

### ISSUE THREAD

**Issue by gserb-datascientist** [PKSHATechnology-Research/camphr#72]
I'm trying to fine-tune NER models emilyalsentzer/Bio_ClinicalBERT and emilyalsentzer/Bio_Discharge_Summary_BERT using below script:

camphr train model.task=ner \
               train.data.path="./train.jsonl" \
               model.labels="./label.json" \
               model.pretrained=emilyalsentzer/Bio_ClinicalBERT  \
               model.lang.name=en
(https://camphr.readthedocs.io/en/latest/notes/finetune_transformers.html)

For both models training failed with:

camphr/pipelines/transformers/auto.py", line 53, in _get_trf_map
raise ValueError(f"Couldn't find any `_TrfMap` from {text}.")
ValueError: Couldn't find any `_TrfMap` from emilyalsentzer/Bio_ClinicalBERT.

The same script finished successfully using simple "bert-base-cased" model.

Should we add additional attributes related to ClinicalBERT models into _TrfMap class  to
ensure they will be accepted for training? 

Thanks,

**Comment by tamuhey** [comment]
Hi, thanks for reporting! I'm updating camphr to use newer verision of transformers now, and will fix this issue in the next version.
